[project]
name = "pdf-text-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fitz>=0.0.1.dev2",
    "pdf2image>=1.17.0",
]
